### PR TITLE
BZ1346242 WFLY-4316 InvalidBytecodeException when an EJB local interface

### PR DESCRIPTION
**Pull request by ppalaga**
declares static method

### CODE REVIEW

**Comment by ppalaga** [comment]
@dmlloyd this is a backport of 505ebd0 to 1.1 because of https://bugzilla.redhat.com/show_bug.cgi?id=1346242

**Comment by samkyatham** [comment]
can this be fixed in wildfly 8.2 too?

**Comment by samkyatham** [comment]
Is this fix below exception that I get it when I use java8 with wildfly 8.2?
 Caused by: org.jboss.classfilewriter.InvalidBytecodeException: Cannot
> load variable at 0. Local Variables: Local Variables: []  at
> org.jboss.classfilewriter.code.CodeAttribute.aload(CodeAttribute.java:185)
>   at
> org.jboss.invocation.proxy.ProxyFactory$ProxyMethodBodyCreator.overrideMethod(ProxyFactory.java:86)
>   at
> org.jboss.invocation.proxy.AbstractSubclassFactory.overrideMethod(AbstractSubclassFactory.java:106)
>   at
> org.jboss.invocation.proxy.AbstractSubclassFactory.addInterface(AbstractSubclassFactory.java:363)
>   at
> org.jboss.invocation.proxy.ProxyFactory.generateClass(ProxyFactory.java:286)
>   at
> org.jboss.invocation.proxy.AbstractClassFactory.buildClassDefinition(AbstractClassFactory.java:207)
>   at
> org.jboss.invocation.proxy.AbstractClassFactory.defineClass(AbstractClassFactory.java:160)
>   at
> org.jboss.invocation.proxy.AbstractProxyFactory.getCachedMethods(AbstractProxyFactory.java:150)
>   at
> org.jboss.as.ejb3.component.stateless.StatelessComponentDescription$3.configure(StatelessComponentDescription.java:150)
>   at
> org.jboss.as.ee.component.DefaultComponentViewConfigurator.configure(DefaultComponentViewConfigurator.java:68)
>   at
> org.jboss.as.ee.component.deployers.EEModuleConfigurationProcessor.deploy(EEModuleConfigurationProcessor.java:81)
>   ... 6 more

**Comment by ppalaga** [comment]
> can this be fixed in wildfly 8.2 too?

If you are asking whether somebody can fix this for you, then the answer is no. If you want to port the fix to an older branch, feel free to ask @dmlloyd if he is ready to accept such a patch.

**Pull request merged**
